# Generated by Django 3.0.4 on 2020-03-17 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='kudos',
            new_name='kudosCount',
        ),
    ]
