# Generated by Django 3.0.4 on 2020-03-19 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200318_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='kudosLastUpdated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
