# Generated by Django 3.0.4 on 2020-03-17 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fromColleague', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromColleage', to=settings.AUTH_USER_MODEL)),
                ('toColleague', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toColleague', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
